CREATE TABLE payment_status (
    payment_status_id SERIAL PRIMARY KEY,
    status_name VARCHAR(20) NOT NULL CHECK ( CHAR_LENGTH(status_name) BETWEEN 2 AND 20),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);