CREATE TABLE order_status (
    order_status_id SERIAL PRIMARY KEY,
    status VARCHAR(100) NOT NULL CHECK (CHAR_LENGTH(status) BETWEEN 2 AND 100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
