services:
  node-app:
    env_file:
      - ./env/development.env
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src:rw
    environment:
      - NODE_ENV=development
