export enum SettingKey {
	/* ─────────── Branding & UI ─────────── */
	SITE_NAME = 'SITE_NAME',
	SITE_LOGO_URL = 'SITE_LOGO_URL',
	PRIMARY_COLOR = 'PRIMARY_COLOR',

	/* ─────────── Localization ─────────── */
	DEFAULT_LANGUAGE = 'DEFAULT_LANGUAGE',
	SUPPORTED_LANGUAGES = 'SUPPORTED_LANGUAGES',
	DEFAULT_CURRENCY = 'DEFAULT_CURRENCY',
	LOCALE_FORMAT_OPTIONS = 'LOCALE_FORMAT_OPTIONS',

	/* ─────────── Platform / Maintenance ─────────── */
	MAINTENANCE_MODE = 'MAINTENANCE_MODE',
	MAINTENANCE_MESSAGE = 'MAINTENANCE_MESSAGE',

	/* ─────────── Orders & Checkout ─────────── */
	MIN_ORDER_AMOUNT = 'MIN_ORDER_AMOUNT',
	MAX_ORDER_ITEMS = 'MAX_ORDER_ITEMS',
	ORDER_CANCELLATION_WINDOW_MIN = 'ORDER_CANCELLATION_WINDOW_MIN',
	ORDER_EXPIRED_AFTER_WINDOW_MIN = 'ORDER_EXPIRED_AFTER_WINDOW_MIN',

	/* ─────────── Delivery Logistics ─────────── */
	DELIVERY_BASE_FEE = 'DELIVERY_BASE_FEE',
	DELIVERY_PER_KM_FEE = 'DELIVERY_PER_KM_FEE',
	DELIVERY_RADIUS_KM = 'DELIVERY_RADIUS_KM',
	DEFAULT_PREPARATION_TIME_MIN = 'DEFAULT_PREPARATION_TIME_MIN',

	/* ─────────── Fees, Tax & Payments ─────────── */
	SERVICE_BASE_FEE = 'SERVICE_BASE_FEE',
	TAX_RATE_PERCENT = 'TAX_RATE_PERCENT',
	ENABLE_CASH_ON_DELIVERY = 'ENABLE_CASH_ON_DELIVERY',

	/* ─────────── Notifications ─────────── */
	PUSH_NOTIFICATIONS_ENABLED = 'PUSH_NOTIFICATIONS_ENABLED',
	ORDER_STATUS_TEMPLATES = 'ORDER_STATUS_TEMPLATES',

	/* ─────────── Support & Ops ─────────── */
	SUPPORT_EMAIL = 'SUPPORT_EMAIL',
	SUPPORT_PHONE = 'SUPPORT_PHONE',
	BUSINESS_HOURS = 'BUSINESS_HOURS',

	/* ─────────── Security & Rate Limits ─────────── */
	PASSWORD_MIN_LENGTH = 'PASSWORD_MIN_LENGTH',
	JWT_EXPIRATION_MIN = 'JWT_EXPIRATION_MIN',
	RATE_LIMIT_PER_MIN = 'RATE_LIMIT_PER_MIN',

	/* ─────────── Integrations / Secrets* ─────────── */
	MAPS_API_CONFIG = 'MAPS_API_CONFIG',
	FIREBASE_CONFIG = 'FIREBASE_CONFIG'
}
